nav:
  - display: Home
    link: /
  - display: Static
    link: /reference
  - display: Realtime
    link: /realtime
  - display: Getting Started
    link: /getting-started
  - display: Examples
    link: /examples
  - display: Testing Feeds
    link: /testing
  - display: Best Practices
    link: /best-practices

pages:
  - title: Home
    url: /
    template: basic-page
    # files:
    #   - pages/home.md
  - title: Static Reference
    url: /reference
    template: doc-page
    sidemenu:
    - name: Term Definitions
      slug: reference
    - name: Field Types
    - name: Feed Files
    - name: File Requirements
    - name: Field Definitions
      children:
      - name: agency.txt
      - name: stops.txt
      - name: routes.txt
      - name: trips.txt
      - name: stop_times.txt
      - name: calendar.txt
      - name: calendar_dates.txt
      - name: fare_attributes.txt
      - name: fare_rules.txt
      - name: shapes.txt
      - name: frequencies.txt
      - name: transfers.txt
      - name: feed_info.txt

  - title: Realtime Reference
    url: /realtime
    template: doc-page
    sidemenu:
    - name: Feed Message
      anchor: /realtime/#message-feedmessage
      slug: reference
      children:
      - name: Feed Header
        anchor: /realtime/#message-feedheader
        children:
        - name: Incrementality
          anchor: /realtime/#enum-incrementality
      - name: Feed Entity
        anchor: /realtime/#message-feedentity
        children:
        - name:	Trip Update
          anchor: /realtime/#message-tripupdate
          children:
            - name: Trip Descriptor
              anchor: /realtime/#message-tripdescriptor
            - name: Vehicle Descriptor
              anchor: /realtime/#message-vehicledescriptor
            - name: Stop Time Update
              anchor: /realtime/#message-stoptimeupdate
        - name: Vehicle Position
          anchor: /realtime/#message-vehicleposition
          children:
            - name: Trip Descriptor
              anchor: /realtime/#message-tripdescriptor
            - name: Vehicle Descriptor
              anchor: /realtime/#message-vehicledescriptor
            - name: Position
              anchor: /realtime/#message-position
            - name: Vehicle Stop Status
              anchor: /realtime/#enum-vehiclestopstatus
            - name: Congestion Level
              anchor: /realtime/#enum-congestionlevel
            - name: Occupancy Status
              anchor: /realtime/#enum-occupancystatus
        - name: Alert
          anchor: /realtime/#message-alert
          children:
            - name: Time Range
              anchor: /realtime/#message-timerange
            - name: Entity Selector
              anchor: /realtime/#message-entityselector
            - name: Cause
              anchor: /realtime/#enum-cause
            - name: Effect
              anchor: /realtime/#enum-effect
            - name: Translated String
              anchor: /realtime/#message-translatedstring

  - title: Best Practices
    url: /best-practices
    template: doc-page
    sidemenu:
    - name: Introduction
      slug: introduction
    - name: Dataset Publishing & General Practices
      slug: publishing
    - name: Recommendations Organized by File
      slug: all-files
      anchor: best-practices/#practice-recommendations-organized-by-file
      children :
        - name: All Files
          file: about.md
        - name: agency.txt
          slug: agency
        - name: stops.txt
          slug: stops
        - name: routes.txt
          slug: routes
        - name: trips.txt
          slug: trips
        - name: stop_times.txt
          slug: stop_times
        - name: calendar.txt
          slug: calendar
        - name: calendar_dates.txt
          slug: calendar_dates
        - name: fare_attributes.txt
          slug: fare_attributes
        - name: fare_rules.txt
          slug: fare_rules
        - name: shapes.txt
          slug: shapes
        - name: feed_info.txt
          slug: feed_info
        - name: frequencies.txt
          slug: frequencies
        - name: transfers.txt
          slug: transfers
    - name: Recommendations Organized by Case
      slug: null
      anchor: best-practices/#practice-recommendations-organized-by-case
      children:
        - name: Loop Routes
          slug: loop-routes
        - name: Lasso Routes
          slug: lasso-routes
        - name: Branches
          slug: branches
    - name: About This Document
      slug: about

  - title: Examples
    url: /examples
    template: basic-page

  - title: Testing
    url: /testing
    template: basic-page

  - title: Getting Started
    url: /getting-started
    template: basic-page

  - title: GTFS Background
    url: /gtfs-background
    template: basic-page

  - title: About
    url: /about
    template: basic-page

  - title: Changes
    url: /changes
    template: basic-page
