version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run:
          name: Fetch reference source repos v2
          command: git clone https://github.com/google/transit src/pages/reference/v2
      - run:
          name: Fetch reference source repos v1
          command: git clone https://github.com/google/transit src/pages/reference/v1 && git -C src/pages/reference/v1 reset eb4b243513abdca8efeaefbf8c264d9d1072ffb6 --hard
      - run:
          name: Fetch best practices repo
          command: git clone --single-branch -b docsv2 https://github.com/MobilityData/gtfs-best-practices src/pages/best-practices
      - run: npm run build
      - deploy:
          name: Deploy to s3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync public s3://gtfs.org/ --delete
            fi
