version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - run: sudo apt-get -y -qq install awscli
      - checkout
      - run: npm install
      - run:
          name: Fetch reference source repos v2
          command: git clone https://github.com/google/transit src/pages/reference/v2
      - run:
          name: Fetch reference source repos v1
          command: git clone https://github.com/google/transit src/pages/reference/v1 && git -C src/pages/reference/v1 reset 33c329b0d07e72744de43319f839810a5df0b439 --hard
      - run:
          name: Fetch best practices repo
          command: git clone --single-branch -b docsv2 https://github.com/MobilityData/gtfs-best-practices src/pages/best-practices
      - run: npm run build
      - deploy:
          name: Deploy to s3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync public s3://staging.gtfs.org/ --delete
            elif [ "${CIRCLE_BRANCH}" == "production" ]; then
              aws s3 sync public s3://gtfs.org/ --delete
            fi
workflows:
  version: 2
  commit:
    jobs:
      - build
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
                - production
    jobs:
      - build
